version: "3"

services:
  wordpress:
    image: wordpress:5.6-php7.4
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user_root
      WORDPRESS_DB_PASSWORD: 123456789
      WORDPRESS_DB_NAME: db_root
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_root
      MYSQL_USER: user_root
      MYSQL_PASSWORD: 123456789
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    restart: always

volumes:
  wordpress:
  db:
