version: "3"

services:
  account:
    build: /Users/thienbh/Documents/TS/core/account
    networks:
      - some-net
    
  purchasing:
    build: /Users/thienbh/Documents/TS/seller/purchasing
    networks:
      - some-net

  gw:
    build: /Users/thienbh/Documents/TS/frontend/api-gateway
    ports:
      - 8080:80
    links:
      - account
      - purchasing
    networks:
      - some-net

networks:
  some-net:
    driver: bridge
